### ISSUE TITLE
[FEAT] 로그인, 스플래쉬 페이지

### ISSUE THREAD

**Issue by 202780** [9oormthon-univ/2024_DANPOON_TEAM_28_FE#17]
### 구현 예정 사항
로그인 페이지, 스플래시 화면 UI를 구현합니다. 백엔드 배포 이후 카카오 로그인 API도 연결합니다.

### Todo
- [x] 로그인 페이지 UI 구현
- [x] 스플래시 화면 UI 구현
- [x] 스플래시 화면 렌더링 타이밍 설정 -> (Auth 가져오는 시간 + 리소스 로딩하는 시간)
- [x] 카카오 로그인 연결 전 초기 세팅(변경 가능!!!)
- [ ] 로그인 페이지에 카카오 로그인 API 연결(백엔드 배포 후 진행 예정)
