### ISSUE TITLE
[FEAT] 라우팅 추가 및 공용 컴포넌트 BottomNav

### ISSUE THREAD

**Issue by 202780** [9oormthon-univ/2024_DANPOON_TEAM_28_FE#5]
### 구현 예정 사항
BottomNav 만들면서 라우팅 설정도 필요할 것 같아 둘 다 작업할 예정입니다.

### Todo
-   [x] createBrowserRouter로 router 추가할 예정
-   [x] BottomNav에 들어가야하는 페이지들 생성
-   [x] 라우팅 설정 완료
-   [x] BottomNav 컴포넌트에 필요한 아이콘 추가
-   [x] BottomNav 구현 완료
